import { createActivityEntry, type WorkspaceSnapshot } from '../../shared/model/index.js';

export function createDefaultSnapshot(): WorkspaceSnapshot {
  return {
    projectName: 'Pixel Squad',
    personas: [
      {
        id: 'frontend',
        title: 'Frontend',
        specialty: 'Interface systems',
        color: '#f25f5c',
        skills: [
          { id: 'ui-systems', label: 'UI Systems', level: 4 },
          { id: 'motion', label: 'Motion', level: 3 },
        ],
      },
      {
        id: 'backend',
        title: 'Backend',
        specialty: 'APIs and runtime orchestration',
        color: '#247ba0',
        skills: [
          { id: 'coordination', label: 'Coordination', level: 4 },
          { id: 'persistence', label: 'Persistence', level: 3 },
        ],
      },
      {
        id: 'tester',
        title: 'Tester',
        specialty: 'Verification and regression pressure',
        color: '#70c1b3',
        skills: [
          { id: 'regression', label: 'Regression', level: 4 },
          { id: 'qa-signoff', label: 'QA Signoff', level: 3 },
        ],
      },
      {
        id: 'lead',
        title: 'Lead',
        specialty: 'Routing and prioritization',
        color: '#ffe066',
        skills: [
          { id: 'planning', label: 'Planning', level: 5 },
          { id: 'prioritization', label: 'Prioritization', level: 5 },
        ],
      },
      {
        id: 'devops',
        title: 'DevOps',
        specialty: 'CI/CD, infra, and deployment',
        color: '#8d6e63',
        skills: [
          { id: 'delivery', label: 'Delivery', level: 4 },
          { id: 'observability', label: 'Observability', level: 3 },
        ],
      },
      {
        id: 'designer',
        title: 'Designer',
        specialty: 'UX research and visual design',
        color: '#ce93d8',
        skills: [
          { id: 'ux-research', label: 'UX Research', level: 4 },
          { id: 'visual-design', label: 'Visual Design', level: 4 },
        ],
      },
    ],
    rooms: [
      {
        id: 'briefing',
        name: 'Briefing Room',
        theme: 'general',
        purpose: 'New work lands here before routing.',
        color: '#ffe066',
        agentIds: ['lead-1'],
      },
      {
        id: 'forge',
        name: 'Frontend Forge',
        theme: 'frontend',
        purpose: 'UI, webview, motion, and layout work.',
        color: '#f25f5c',
        agentIds: ['frontend-1'],
      },
      {
        id: 'engine',
        name: 'Backend Engine',
        theme: 'backend',
        purpose: 'Coordinator, API, and persistence work.',
        color: '#247ba0',
        agentIds: ['backend-1', 'tester-1'],
      },
    ],
    agents: [
      {
        id: 'lead-1',
        name: 'Atlas',
        personaId: 'lead',
        provider: 'copilot',
        status: 'planning',
        roomId: 'briefing',
        summary: 'Breaking the product into rooms, adapters, and task flows.',
        spriteVariant: 0,
      },
      {
        id: 'frontend-1',
        name: 'Nova',
        personaId: 'frontend',
        provider: 'copilot',
        status: 'idle',
        roomId: 'forge',
        summary: 'Ready for UI and webview tasks.',
        spriteVariant: 1,
      },
      {
        id: 'backend-1',
        name: 'Tern',
        personaId: 'backend',
        provider: 'claude',
        status: 'idle',
        roomId: 'engine',
        summary: 'Ready for API and runtime tasks.',
        spriteVariant: 2,
      },
      {
        id: 'tester-1',
        name: 'Mica',
        personaId: 'tester',
        provider: 'copilot',
        status: 'idle',
        roomId: 'engine',
        summary: 'Ready for verification and testing tasks.',
        spriteVariant: 3,
      },
    ],
    tasks: [
      {
        id: 'task-1',
        title: 'Bootstrap extension host',
        status: 'done',
        assigneeId: 'backend-1',
        provider: 'claude',
        source: 'factory',
        detail: 'Command, view container, bundle entry, and icon are defined.',
        progress: { value: 3, total: 3, label: 'Complete' },
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        id: 'task-2',
        title: 'Render first agent factory',
        status: 'done',
        assigneeId: 'frontend-1',
        provider: 'copilot',
        source: 'factory',
        detail: 'Rooms, personas, and tasks are visible in the panel.',
        progress: { value: 3, total: 3, label: 'Complete' },
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        id: 'task-3',
        title: 'Wire multi-provider planning pipeline',
        status: 'done',
        assigneeId: 'lead-1',
        provider: 'copilot',
        source: 'factory',
        detail: 'Task routing uses GitHub Copilot or Claude for planning.',
        progress: { value: 3, total: 3, label: 'Complete' },
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
    ],
    runs: [],
    agentSessions: [],
    providers: [
      {
        provider: 'copilot',
        state: 'ready',
        detail: 'GitHub Copilot powers planning and task execution.',
      },
      {
        provider: 'claude',
        state: 'ready',
        detail: 'Claude powers planning and task execution.',
      },
    ],
    activityFeed: [
      createActivityEntry('Pixel Squad coordinator online.', 'system'),
      createActivityEntry('Dual-provider mode: Copilot + Claude.', 'provider', { provider: 'copilot' }),
      createActivityEntry('Factory ready — create rooms and spawn agents to begin.', 'system'),
    ],
    roomFeeds: {},
    settings: {
      autoExecute: false,
      forceMcpForAllTasks: false,
      modelFamily: 'copilot',
      autoPopulateWorkspaceContext: true,
      workspaceContextMaxFiles: 3,
    },
    ui: {
      activeAgentId: 'lead-1',
    },
  };
}
